create table recipes (
    id INTEGER primary key generated by default as identity,
    title TEXT NOT NULL,
    image_url TEXT, 
    ingredients TEXT[] NOT NULL,
    instructions TEXT[] NOT NULL,
    macro TEXT, 
    cuisineType TEXT, 
    recipeType TEXT,
    nutrient_into TEXT,
    source_url TEXT

);